---


# Instalação do Vagrant

- name: Instalando o Vagrant
  apt:
    deb: "https://releases.hashicorp.com/vagrant/{{ vagrant_version_dir }}/vagrant_{{ vagrant_version_bin }}_{{ ansible_architecture }}.deb"
    state: present
    update_cache: yes
  become: true
  tags:
    - vagrant