---


# Instalando o Vagrant

- name: Instalando o Vagrant
  dnf:
    name: "https://releases.hashicorp.com/vagrant/{{ vagrant_version_dir }}/vagrant_{{ vagrant_version_bin }}_{{ ansible_architecture }}.rpm"
    state: present
    disable_gpg_check: yes
  become: true
  tags:
    - vagrant