---


# Instalando o Vagrant

- name: Instalando o Vagrant
  zypper:
    name: "https://releases.hashicorp.com/vagrant/{{ vagrant_version_dir }}/vagrant-{{ vagrant_version_bin }}.{{ ansible_architecture }}.rpm"
    state: present
    update_cache: yes
    disable_gpg_check: yes
  become: true
  tags:
    - vagrant